---
- name: Kubeadm on master
  hosts: single_master
  become: yes
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Get ansible_user home directory
      shell: 'getent passwd "{{ansible_ssh_user}}" | cut -d: -f6'
      register: ansible_home_result
      
    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ansible_home_result.stdout}}'
      
    - name: Create dir if missing
      file: path={{ ansible_home }}/.kube owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory
    
    - name: Check if kubeadm init was done
      stat: path={{ ansible_home }}/.kube/kubeadm-init.output
      register: f
      
    - name: kubeadm init
      shell: kubeadm init > {{ ansible_home }}/.kube/kubeadm-init.output
      when: not f.stat.exists
    
    - name: copy k8s admin config
      shell: cp -i /etc/kubernetes/admin.conf {{ ansible_home }}/.kube/config
      when: not f.stat.exists  
    
    - name: change owner and group of admin config
      shell: chown $(id -u {{ ansible_ssh_user }}):$(id -g {{ ansible_ssh_user }}) {{ ansible_home }}/.kube/config
      when: not f.stat.exists  
    
    - name: create join script
      shell: grep 'kubeadm join' {{ ansible_home }}/.kube/kubeadm-init.output > /tmp/join_cmd.sh
      when: not f.stat.exists
    
    - name: change owner and group of join_cmd.sh
      file: path=/tmp/join_cmd.sh owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
      when: not f.stat.exists
