---
- name: Prep Ubuntu
  hosts: nodes
  become: yes
  gather_facts: True
  vars_files:
    - ../answerfile.yml
    - ../defaults.yml    
  tasks:    
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
        state: present
      with_items: "{{ groups.nodes }}"

    - name: Check if SSH key exists
      stat: path=~/.ssh/id_rsa
      register: stat
      
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
      ignore_errors: yes
      when: not stat.stat.exists
      
    - name: Disable swap
      shell: swapoff -a

    - name: Change fstab not to enable swap
      shell: sed -i '/ swap / s/^/#/' /etc/fstab
  
    - name: install required packages
      apt: name={{ item }} update_cache=yes
      with_items: "{{ ubuntu.required_package }}"

    - name: Set ntp server
      shell: sed -i 's/#NTP=/NTP="{{ ntp }}"/g' /etc/systemd/timesyncd.conf
  
    - name: Restart timesyncd 
      service: name=systemd-timesyncd state=restarted enabled=yes

    - name: add google repo key
      shell: 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -'

    - name: Add kubernete repo
      lineinfile:
        state: present
        create: yes
        dest: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        
    - name: install kubeadm
      apt: name={{ item }} update_cache=yes
      with_items:
        - kubelet=1.10.3-00
        - kubeadm=1.10.3-00
        - kubectl=1.10.3-00
