---
- name: Deploy NSX - T Components
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Deploy NSX-T manager
      nsxt_deploy:
        component: 'manager'
        datastore: "{{ vcenter.management_datastore }}"
        network: "{{ vcenter.management_portgroup }}"
        cluster: "{{ vcenter.management_cluster }}"        
        netmask : "{{ management_network.netmask }}"
        gateway: "{{ management_network.gateway }}"
        dns: "{{ dns }}"
        domain: "{{ domain }}"
        ntp: "{{ ntp }}"
        name: "{{ nsxt_manager.name }}"
        ip: "{{ nsxt_manager.ip }}"
        password: "{{ nsxt_manager.password }}"
        ova: "{{ nsxt_manager.ova }}"
        vcenter_username: "{{ vcenter.username }}"
        vcenter_password: "{{ vcenter.password }}"
        vcenter_ip: "{{ vcenter.ip }}"
        datacenter: "{{ vcenter.datacenter }}"
        size: "{{ nsxt_manager.ip }}"
        
    - name: Deploy NSX-T controller
      nsxt_deploy:
        component: 'controller'
        datastore: "{{ vcenter.management_datastore }}"
        network: "{{ vcenter.management_portgroup }}"
        cluster: "{{ vcenter.management_cluster }}"        
        netmask : "{{ management_network.netmask }}"
        gateway: "{{ management_network.gateway }}"
        dns: "{{ dns }}"
        domain: "{{ domain }}"
        ntp: "{{ ntp }}"
        name: "{{ item.key }}"
        ip: "{{ item.value.ip }}"
        password: "{{ item.value.password }}"
        ova: "{{ item.value.ova }}"
        vcenter_username: "{{ vcenter.username }}"
        vcenter_password: "{{ vcenter.password }}"
        vcenter_ip: "{{ vcenter.ip }}"
        datacenter: "{{ vcenter.datacenter }}"

      with_dict: "{{ nsxt_controller }}"


    - name: Deploy NSX-T edge
      nsxt_deploy:
        component: 'edge'
        datastore: "{{ vcenter.management_datastore }}"
        network: "{{ vcenter.management_portgroup }}"
        cluster: "{{ vcenter.management_cluster }}"        
        netmask : "{{ management_network.netmask }}"
        gateway: "{{ management_network.gateway }}"
        dns: "{{ dns }}"
        domain: "{{ domain }}"
        ntp: "{{ ntp }}"
        name: "{{ item.key }}"
        ip: "{{ item.value.ip }}"
        password: "{{ item.value.password }}"
        ova: "{{ item.value.ova }}"
        vcenter_username: "{{ vcenter.username }}"
        vcenter_password: "{{ vcenter.password }}"
        vcenter_ip: "{{ vcenter.ip }}"
        datacenter: "{{ vcenter.datacenter }}"
        overlay_network: "{{ item.value.overlay_network }}"
        vlan_network: "{{ item.value.vlan_network }}"
        size: "{{ item.value.size }}"
      with_dict: "{{ nsxt_edge }}"
      
