---
- name: Kubeadm on workers
  hosts: workers
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Create dir if missing
      file: path={{ ansible_env.HOME }}/.kube owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory
    
    - name: Check if node joined
      stat: path={{ ansible_env.HOME }}/.kube/joined
      register: f
    
    - name: Copy join_cmd.sh from master to nodes
      shell: sshpass -p "{{ k8s.password }}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "{{ k8s.master_node }}:/tmp/join_cmd.sh" /tmp/join_cmd.sh
      when: not f.stat.exists      
      
    - name: join to the clsuter
      become: yes
      shell: /bin/bash /tmp/join_cmd.sh > {{ ansible_env.HOME }}/.kube/joined
      when: not f.stat.exists      
